private _unitLoadoutArray =


[["Platoon Commander@PLATOON",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_grassland",
"cnto_flecktarn_b_ap_grassland",
"cnto_flecktarn_h_s_grassland",
"rhs_weap_hk416d145_m320",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","1Rnd_SmokeRed_Grenade_shell","","rhsusf_acc_anpeq16a","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","ACE_VectorDay",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"],
[2,"ACE_CableTie"],
[1,"ACE_MapTools"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[4,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[6,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[1,"ACRE_PRC148"],
[1,"ACRE_PRC152"],
[1,"ACE_IR_Strobe_Item"],
[2,"SmokeShellBlue"],
[5,"SmokeShellGreen"],
[3,"SmokeShell"],
[5,"1_Rnd_Smoke_Grenade_shell"],
[5,"1_Rnd_SmokeRed_Grenade_shell"],
[5,"1_Rnd_SmokeRed_Grenade_shell"]
],
[
[0,""]
]],
["Platoon Sergeant",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_l_grassland",
"UK3CB_B_O_Radio_Backpack",
"cnto_flecktarn_h_s_grassland",
"rhs_weap_hk416d10",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","ACE_VectorDay",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"],
[1,"ACRE_PRC152"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[2,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[8,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[1,"ACRE_PRC117F"]
],
[
[0,""]
]],
["Platoon Medic",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_grassland",
"cnto_flecktarn_b_kb_grassland",
"cnto_flecktarn_h_c_grassland",
"rhs_weap_hk416d10",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[2,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[8,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[10,"ACE_fieldDressing"],
[30,"ACE_elasticBandage"],
[20,"ACE_packingBandage"],
[10,"ACE_quikclot"],
[2,"ACE_bloodIV"],
[8,"ACE_bloodIV_500"],
[5,"ACE_adenosine"],
[15,"ACE_epinephrine"],
[15,"ACE_morphine"],
[1,"ACE_surgicalKit"],
[6,"ACE_tourniquet"],
[8,"SmokeShell"],
[2,"SmokeShellGreen"]
],
[
[0,""]
]],
["Platoon Rifleman",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_l_grassland",
"",
"cnto_flecktarn_h_c_grassland",
"rhs_weap_hk416d145",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[2,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[8,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[0,""]
],
[
[0,""]
]],
["Squad Leader",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_grassland",
"cnto_flecktarn_b_ap_grassland",
"cnto_flecktarn_h_s_grassland",
"rhs_weap_hk416d145_m320",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","1Rnd_HE_Grenade_shell","","rhsusf_acc_anpeq16a","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","ACE_VectorDay",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"],
[2,"ACE_CableTie"],
[1,"ACE_MapTools"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[4,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[6,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[1,"ACE_IR_Strobe_Item"],
[4,"1_Rnd_HE_Grenade_shell"],
[4,"1_Rnd_Smoke_Grenade_shell"],
[4,"1_Rnd_SmokeRed_Grenade_shell"],
[4,"1_Rnd_SmokeRed_Grenade_shell"],
[2,"SmokeShellBlue"],
[5,"SmokeShellGreen"],
[3,"SmokeShell"],
[1,"ACRE_PRC152"]
],
[
[0,""]
]],
["Squad Medic",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_grassland",
"cnto_flecktarn_b_kb_grassland",
"cnto_flecktarn_h_c_grassland",
"rhs_weap_hk416d10",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","ACE_VectorDay",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[2,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[8,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[10,"ACE_fieldDressing"],
[30,"ACE_elasticBandage"],
[20,"ACE_packingBandage"],
[10,"ACE_quikclot"],
[2,"ACE_bloodIV"],
[8,"ACE_bloodIV_500"],
[5,"ACE_adenosine"],
[15,"ACE_epinephrine"],
[15,"ACE_morphine"],
[1,"ACE_surgicalKit"],
[6,"ACE-tourniquet"],
[8,"SmokeShell"],
[2,"SmokeShellGreen"]
],
[
[0,""]
]],
["Fireteam Leader",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_grassland",
"cnto_flecktarn_b_ap_grassland",
"cnto_flecktarn_h_s_grassland",
"rhs_weap_hk416d145_m320",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","1Rnd_HE_Grenade_shell","","rhsusf_acc_anpeq16a","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","ACE_VectorDay",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"],
[2,"ACE_CableTie"],
[1,"ACE_MapTools"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[4,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[6,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[1,"ACE_IR_Strobe_Item"],
[8,"1_Rnd_HE_Grenade_shell"],
[5,"1_Rnd_Smoke_Grenade_shell"],
[5,"1_Rnd_SmokeRed_Grenade_shell"],
[2,"SmokeShellBlue"],
[5,"SmokeShellGreen"],
[3,"SmokeShell"]
],
[
[0,""]
]],
["Autorifleman",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_l_grassland",
"cnto_flecktarn_b_ap_grassland",
"cnto_flecktarn_h_c_grassland",
"rhs_weap_minimi_para_railed",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","","rhsusf_acc_sf3p556","","","rhsusf_acc_saw_bipod"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","","ItemCompass","ItemWatch","",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[3,"rhsusf_100Rnd_556x45_soft_pouch"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[3,"rhsusf_100Rnd_556x45_soft_pouch"]
],
[
[0,""]
]],
["Assist. autorifleman",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_grassland",
"cnto_flecktarn_b_kb_grassland",
"cnto_flecktarn_h_c_grassland",
"rhs_weap_hk416d145",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","ACE_VectorDay",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"],
[2,"ACE_CableTie"],
[1,"ACE_MapTools"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[4,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[6,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[2,"rhsusf_100Rnd_556x45_soft_pouch"]
],
[
[0,""]
]],
["Rifleman AT",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_l_grassland",
"",
"cnto_flecktarn_h_c_grassland",
"rhs_weap_hk416d10",
"hlc_pistol_P226R_357Elite",
"rhs_weap_m72a7",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","","ItemCompass","ItemWatch","",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[2,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[8,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[0,""]
],
[
[0,""]
]],
["MMG Team Leader@MEDIUM MACHINE GUN",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_grassland",
"cnto_flecktarn_b_ap_grassland",
"cnto_flecktarn_h_s_grassland",
"rhs_weap_hk416d145_m320",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","1Rnd_HE_Grenade_shell","","rhsusf_acc_anpeq16a","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"],
[2,"ACE_CableTie"],
[1,"ACE_MapTools"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[4,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[6,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[1,"ACE_IR_Strobe_Item"],
[4,"1_Rnd_HE_Grenade_shell"],
[4,"1_Rnd_Smoke_Grenade_shell"],
[4,"1_Rnd_SmokeRed_Grenade_shell"],
[4,"1_Rnd_SmokeRed_Grenade_shell"],
[2,"SmokeShellBlue"],
[5,"SmokeShellGreen"],
[3,"SmokeShell"],
[1,"ACRE_PRC152"]
],
[
[0,""]
]],
["MMG Gunner",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_l_grassland",
"cnto_flecktarn_b_kb_grassland",
"cnto_flecktarn_h_c_grassland",
"BWA3_MG5",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","","ItemCompass","ItemWatch","",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[4,"BWA3_120Rnd_762x51_soft"]
],
[
[0,""]
]],
["MMG Ammo Bearer",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_l_grassland",
"cnto_flecktarn_b_kb_grassland",
"cnto_flecktarn_h_c_grassland",
"rhs_weap_hk416d145",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","","ItemCompass","ItemWatch","",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[2,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[8,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[4,"BWA3_120Rnd_762x51_soft"]
],
[
[0,""]
]],
["MAT Team Leader@MEDIUM ANTI-TANK",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_grassland",
"cnto_flecktarn_b_ap_grassland",
"cnto_flecktarn_h_s_grassland",
"rhs_weap_hk416d145_m320",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","1Rnd_HE_Grenade_shell","","rhsusf_acc_anpeq16a","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","ACE_VectorDay",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"],
[2,"ACE_CableTie"],
[1,"ACE_MapTools"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[4,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[6,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[1,"ACE_IR_Strobe_Item"],
[4,"1_Rnd_HE_Grenade_shell"],
[4,"1_Rnd_Smoke_Grenade_shell"],
[4,"1_Rnd_SmokeRed_Grenade_shell"],
[4,"1_Rnd_SmokeRed_Grenade_shell"],
[2,"SmokeShellBlue"],
[5,"SmokeShellGreen"],
[3,"SmokeShell"],
[1,"ACRE_PRC152"]
],
[
[0,""]
]],
["MAT Gunner",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_l_grassland",
"cnto_flecktarn_b_ap_grassland",
"cnto_flecktarn_h_c_grassland",
"rhs_weap_hk416d145",
"hlc_pistol_P226R_357Elite",
"launch_MRAWS_olive_rail_F",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["MRAWS_HEAT_F","","","",""],
 ["ItemMap","","ItemCompass","ItemWatch","",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[2,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[8,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[1,"MRAWS_HE_F"],
[2,"MRAWS_HEAT_F"]
],
[
[0,""]
]],
["MAT Ammo Bearer",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_l_grassland",
"cnto_flecktarn_b_ap_grassland",
"cnto_flecktarn_h_c_grassland",
"rhs_weap_hk416d145",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","","ItemCompass","ItemWatch","",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[2,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[8,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[1,"MRAWS_HE_F"],
[2,"MRAWS_HEAT_F"]
],
[
[0,""]
]],
["Engineer Team Leader@ENGINEERS",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_h_grassland",
"cnto_flecktarn_b_ca_grassland",
"cnto_flecktarn_h_s_grassland",
"rhs_weap_hk416d145_m320",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","1Rnd_HE_Grenade_shell","","rhsusf_acc_anpeq16a","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","ACE_VectorDay",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"],
[2,"ACE_CableTie"],
[1,"ACE_MapTools"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[4,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[6,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[1,"ToolKit"]
],
[
[0,""]
]],
["Engineer Rifleman",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_h_grassland",
"cnto_flecktarn_b_ca_grassland",
"cnto_flecktarn_h_c_grassland",
"rhs_weap_hk416d145",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","ACE_VectorDay",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[2,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[8,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[1,"ToolKit"]
],
[
[0,""]
]],
["DMT Team Leader@DESIGNATED MARKSMAN TEAM",
"cnto_flecktarn_u_t_grassland",
"cnto_flecktarn_v_l_grassland",
"",
"cnto_flecktarn_h_boo_grassland",
"rhs_weap_hk416d10_m320",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","1Rnd_HE_Grenade_shell","","rhsusf_acc_anpeq16a","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"],
[2,"ACE_CableTie"],
[1,"ACE_MapTools"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[4,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[6,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"],
[1,"ACE_microDAGR"],
[1,"ACE_HuntIR_monitor"],
[1,"ACE_IR_Strobe_Item"]
],
[
[0,""]
],
[
[0,""]
]],
["DMT Marksman",
"cnto_flecktarn_u_t_grassland",
"cnto_flecktarn_v_l_grassland",
"",
"cnto_flecktarn_h_boo_grassland",
"hlc_rifle_PSG1A1_RIS",
"hlc_pistol_P226R_357Elite",
"",
 ["hlc_20rnd_762x51_Mk316_G3","","","","rhsusf_acc_acog3_usmc","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"],
[2,"ACE_CableTie"],
[1,"ACE_MapTools"],
[1,"ACE_Kestrel4500"],
[1,"ACE_microDAGR"],
[1,"ACE_RangeCard"],
[2,"SmokeShell"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[4,"hlc_20rnd_762x51_Mk316_G3"],
[1,"ACE_IR_Strobe_Item"]
],
[
[0,""]
],
[
[0,""]
]],
["Mortar Ass. Gunner@MORTAR",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_grassland",
"B_Mortar_01_support_F",
"cnto_flecktarn_h_c_grassland",
"rhs_weap_hk416d10_m320",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","1Rnd_HE_Grenade_shell","rhsusf_acc_nt4_black","rhsusf_acc_anpeq16a","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC152"],
[1,"ACRE_PRC343"],
[2,"ACE_CableTie"],
[1,"ACE_MapTools"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[2,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[8,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"],
[1,"SmokeShellBlue"],
[2,"SmokeShellGreen"]
],
[
[0,""]
],
[
[0,""]
]],
["Mortar Gunner",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_grassland",
"B_Mortar_01_weapon_F",
"cnto_flecktarn_h_c_grassland",
"rhs_weap_hk416d10",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"],
[2,"ACE_CableTie"],
[1,"ACE_MapTools"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[2,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[8,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[0,""]
],
[
[0,""]
]],
["Vehicle Commander: Dagger@DAGGER",
"NatoU_Green_rs",
"TacVest_black",
"",
"H_HelmetCrew_I",
"hlc_smg_mp5k_PDW",
"hlc_pistol_P226R_357Elite",
"",
 ["hlc_30Rnd_9x19_B_MP5","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","ACE_Vector","ACE_NVG_Wide"],
[
[1,"ACRE_PRC148"],
[1,"ACRE_PRC152"],
[1,"ACRE_PRC343"],
[10,"ACE_quikclot"],
[1,"ACE_epinephrine"],
[1,"ACE_MapTools"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"]
],
[
[4,"hlc_30Rnd_9x19_B_MP5"],
[2,"HandGrenade"],
[2,"SmokeShellBlue"],
[2,"SmokeShellGreen"],
[2,"SmokeShell"]
],
[
[0,""]
],
[
[0,""]
]],
["Vehicle Driver: Dagger",
"NatoU_Green_rs",
"TacVest_black",
"B_AssaultPack_rgr",
"H_HelmetCrew_I",
"hlc_smg_mp5k_PDW",
"hlc_pistol_P226R_357Elite",
"",
 ["hlc_30Rnd_9x19_B_MP5","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","ACE_Vector","ACE_NVG_Wide"],
[
[1,"ACRE_PRC343"],
[10,"ACE_quikclot"],
[1,"ACE_epinephrine"],
[1,"ACE_MapTools"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"]
],
[
[4,"hlc_30Rnd_9x19_B_MP5"],
[2,"HandGrenade"],
[2,"SmokeShellBlue"],
[2,"SmokeShellGreen"],
[2,"SmokeShell"]
],
[
[1,"ToolKit"]
],
[
[0,""]
]],
["Vehicle Gunner: Dagger",
"NatoU_Green_rs",
"TacVest_black",
"",
"H_HelmetCrew_I",
"hlc_smg_mp5k_PDW",
"hlc_pistol_P226R_357Elite",
"",
 ["hlc_30Rnd_9x19_B_MP5","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","ACE_Vector","ACE_NVG_Wide"],
[
[1,"ACRE_PRC343"],
[10,"ACE_quikclot"],
[1,"ACE_epinephrine"],
[1,"ACE_MapTools"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"]
],
[
[4,"hlc_30Rnd_9x19_B_MP5"],
[2,"HandGrenade"],
[2,"SmokeShellBlue"],
[2,"SmokeShellGreen"],
[2,"SmokeShell"]
],
[
[0,""]
],
[
[0,""]
]],
["Pilot: Nightbird@NIGHTBIRD",
"NatoU_Atacs",
"TacVest_black",
"",
"H_PilotHelmetHeli_B",
"hlc_smg_mp5k_PDW",
"hlc_pistol_P226R_357Elite",
"",
 ["hlc_30Rnd_9x19_B_MP5","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","ACE_Vector","ACE_NVG_Wide"],
[
[1,"ACRE_PRC148"],
[1,"ACRE_PRC152"],
[1,"ACRE_PRC343"],
[10,"ACE_quikclot"],
[1,"ACE_epinephrine"],
[1,"ACE_MapTools"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"]
],
[
[4,"hlc_30Rnd_9x19_B_MP5"],
[2,"HandGrenade"],
[2,"SmokeShellBlue"],
[2,"SmokeShellGreen"],
[2,"SmokeShell"]
],
[
[1,"ToolKit"]
],
[
[0,""]
]],
["Co-Pilot: Nightbird",
"NatoU_Atacs",
"TacVest_black",
"B_AssaultPack_rgr",
"H_PilotHelmetHeli_B",
"hlc_smg_mp5k_PDW",
"hlc_pistol_P226R_357Elite",
"",
 ["hlc_30Rnd_9x19_B_MP5","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","ACE_Vector","ACE_NVG_Wide"],
[
[1,"ACRE_PRC148"],
[1,"ACRE_PRC152"],
[1,"ACRE_PRC343"],
[10,"ACE_quikclot"],
[1,"ACE_epinephrine"],
[1,"ACE_MapTools"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"]
],
[
[4,"hlc_30Rnd_9x19_B_MP5"],
[2,"HandGrenade"],
[2,"SmokeShellBlue"],
[2,"SmokeShellGreen"],
[2,"SmokeShell"]
],
[
[1,"ToolKit"]
],
[
[0,""]
]],
["Jet Pilot: Falcon@FALCON",
"NatoU_Atacs",
"TacVest_black",
"B_Parachute",
"H_PilotHelmetFighter_I",
"hlc_smg_mp5k_PDW",
"hlc_pistol_P226R_357Elite",
"",
 ["hlc_30Rnd_9x19_B_MP5","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","ACE_Vector",""],
[
[1,"ACRE_PRC148"],
[1,"ACRE_PRC152"],
[1,"ACRE_PRC343"],
[10,"ACE_quikclot"],
[1,"ACE_epinephrine"],
[1,"ACE_MapTools"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"]
],
[
[4,"hlc_30Rnd_9x19_B_MP5"],
[2,"HandGrenade"],
[2,"SmokeShellBlue"],
[2,"SmokeShellGreen"],
[2,"SmokeShell"]
],
[
[0,""]
],
[
[0,""]
]],
["Game Master",
"cnto_flecktarn_u_grassland",
"cnto_flecktarn_v_grassland",
"cnto_flecktarn_b_ap_grassland",
"cnto_flecktarn_h_c_grassland",
"rhs_weap_hk416d145",
"hlc_pistol_P226R_357Elite",
"",
 ["rhs_mag_30Rnd_556x45_M855A1_Stanag","","","","","rhsusf_acc_grip2"],
 ["hlc_12Rnd_357SIG_B_P226","","","",""],
 ["","","","",""],
 ["ItemMap","ItemGPS","ItemCompass","ItemWatch","ACE_Vector",""],
[
[4,"ACE_fieldDressing"],
[1,"ACE_epinephrine"],
[6,"ACE_quikclot"],
[1,"ACE_morphine"],
[2,"ACE_tourniquet"],
[1,"rhsusf_acc_M952V"],
[1,"ACRE_PRC343"],
[2,"ACE_CableTie"],
[1,"ACE_MapTools"]
],
[
[1,"hlc_12Rnd_357SIG_B_P226"],
[4,"rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red"],
[6,"rhs_mag_30Rnd_556x45_M855A1_Stanag"],
[2,"HandGrenade"],
[4,"SmokeShell"]
],
[
[1,"ACRE_PRC148"],
[1,"ACRE_PRC152"],
[1,"ACE_IR_Strobe_Item"],
[2,"SmokeShellBlue"],
[5,"SmokeShellGreen"],
[3,"SmokeShell"],
[5,"1_Rnd_Smoke_Grenade_shell"],
[5,"1_Rnd_SmokeRed_Grenade_shell"],
[5,"1_Rnd_SmokeRed_Grenade_shell"]
],
[
[0,""]
]]];


private _loadoutArrayExample = {
[
   [
      "description",
      "uniform",
      "vest",
      "backpack",
      "headgear",
      "primary weapon",
      "secondary weapon",
      "launcher",
      ["primary weapon accessories array"],
      ["secondary weapon accessories array"],
      ["launcher accessories array"],
      ["items array (map, gps etc)"],
      [
         [0,"uniformItems"]
      ],
      [
         [0,"vestItems"]
      ],
      [
         [0,"backPackItems"]
      ],
      [
         [0,"anywhereItems"]
      ]
   ]
];
};

private _fnc_addItem = {
params ["_unit","_item",["_amount",1],["_where","any"]];

   switch (_where) do {
      case "uniform": {
         for "_i" from 1 to _amount do {
            _unit addItemToUniform _item;
         };
      };
      case "vest": {
         for "_i" from 1 to _amount do {
            _unit addItemToVest _item;
         };
      };
      case "backpack": {
         for "_i" from 1 to _amount do {
            _unit addItemtoBackpack _item;
         };
      };
      default {
         for "_i" from 1 to _amount do {
            _unit addItem _item;
         };
      };
   };
};

{
   private _unit = _x;
   // get unit description and empty their inventory
   private _unitDescription = _unit get3DENAttribute "description" select 0;
   _unit setUnitLoadout [[],[],[],[],[],[],"","",[],["","","","","",""]];
   {
      private _newLoadout = _x;
      _newLoadout params ["_targetDescription","_uniform","_vest","_backpack","_headgear","_primaryWeapon","_handgunWeapon","_launcher","_primaryAccessories","_handgunAccessories","_launcherAccessories","_equipment","_uniformArray","_vestArray","_backpackArray","_anywhereArray"];

      if (_targetDescription in _unitDescription) then {

         // add uniform items

         _unit addVest _vest;
         _unit forceAddUniform _uniform;
         _unit addBackpack _backpack;
         _unit addHeadGear _headgear;

         // add equipment

         {
            _unit linkItem _x;
         } forEach _equipment;

         // add weapons and weapon items (including magazines)

         _unit addWeapon _primaryWeapon;
         _unit addWeapon _handgunWeapon;
         _unit addWeapon _launcher;
         {
            _unit addPrimaryWeaponItem _x;
         } forEach _primaryAccessories;
         {
            _unit addHandGunItem _x;
         } forEach _handgunAccessories;
         {
            _unit addSecondaryWeaponItem _x;
         } forEach _launcherAccessories;

         // all the rest of the items

         {
            _x params ["_amount","_item"];
            [_unit,_item,_amount,"vest"] call _fnc_addItem;
         } forEach _vestArray;
         {
            _x params ["_amount","_item"];
            [_unit,_item,_amount,"uniform"] call _fnc_addItem;
         } forEach _uniformArray;
         {
            _x params ["_amount","_item"];
            [_unit,_item,_amount,"backpack"] call _fnc_addItem;
         } forEach _backpackArray;
         {
            _x params ["_amount","_item"];
            [_unit,_item,_amount,"any"] call _fnc_addItem;
         } forEach _anywhereArray;

      };
   } forEach _unitLoadoutArray;
} forEach playableUnits;
save3DENInventory playableUnits;																									